FROM jenkins/jenkins:lts

USER root

RUN apt-get update && apt-get install -y docker.io

RUN groupadd -f docker && usermod -aG docker jenkins

RUN chmod 666 /var/run/docker.sock || true

RUN jenkins-plugin-cli --plugins \
    docker-workflow \
    git \
    credentials-binding \
    workflow-aggregator

USER jenkins
